### ISSUE TITLE
Porblems with snakefile. WorkflowError in line 7. 

### ISSUE THREAD

**Issue by hqs10** [nanoporetech/pipeline-transcriptome-de#12]
Hi all,

Having the following issue with the workflow:

tardig@DESKTOP-NEKU62R:~/pipeline-transcriptome-de$ snakemake --use-conda -j 4 all
WorkflowError in line 7 of /home/tardig/pipeline-transcriptome-de/Snakefile:
Config file is not valid JSON or YAML. In case of YAML, make sure to not mix whitespace and tab indentation.
  File "/home/tardig/pipeline-transcriptome-de/Snakefile", line 7, in <module>

Please find snakefile and config files attached.

[config.txt](https://github.com/nanoporetech/pipeline-transcriptome-de/files/4102936/config.txt)

[Snakefile.txt](https://github.com/nanoporetech/pipeline-transcriptome-de/files/4102931/Snakefile.txt)

Thanks,

Stan

**Comment by m-noonan** [comment]
I'm having this same issue, how did you resolve this?
