### ISSUE TITLE
Error in running de_analysis script

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pipeline-transcriptome-de#14]
Based on coldata.tsv, seems OK 

[config.yml.txt](https://github.com/nanoporetech/pipeline-transcriptome-de/files/4225856/config.yml.txt)

`rule de_analysis:
    input: de_analysis/de_params.tsv, de_analysis/coldata.tsv, merged/all_counts.tsv
    output: de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv
    jobid: 3

Loading counts, conditions and parameters.
Loading annotation database.
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 3, 5, 4, 7, 6
Calls: strip_version ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>
Execution halted
Error in job de_analysis while creating output files de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv.
RuleException:
CalledProcessError in line 137 of /home/callum/pipeline-transcriptome-de/Snakefile:
Command '
    /home/callum/pipeline-transcriptome-de/scripts/de_analysis.R
    ' returned non-zero exit status 1.
  File "/home/callum/pipeline-transcriptome-de/Snakefile", line 137, in __rule_de_analysis
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
`

**Comment by bsipos** [comment]
Have you still got the merged counts? Do they look all right?

**Comment by callumparr** [comment]
They look good to me. 

[all_counts.tsv.txt](https://github.com/nanoporetech/pipeline-transcriptome-de/files/4229929/all_counts.tsv.txt)
[coldata.tsv.txt](https://github.com/nanoporetech/pipeline-transcriptome-de/files/4229930/coldata.tsv.txt)

**Comment by bsipos** [comment]
It seems you have modified the sequence headers in the transcriptome fasta. Now the IDs include extra stuff which breaks the pipeline. Please use the original tarnscriptome fasta from Ensembl.

**Comment by callumparr** [comment]
Ah OK I was using the gencode transcriptome. I will re run with the Ensembl version. Thank you. Will close once confirm it works.
