### ISSUE TITLE
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])

### ISSUE THREAD

**Issue by suvimake** [nanoporetech/pipeline-transcriptome-de#15]
Hi!
I get the following error message with error in contrasts:

Loading counts, conditions and parameters.
Loading annotation database.
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Filtering counts using DRIMSeq.
Building model matrix.
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Calls: model.matrix -> model.matrix.default -> contrasts<-
Execution halted
[Sun Jul  5 21:59:33 2020]
Error in rule de_analysis:
    jobid: 9

I'm not sure how to fix this? I only have two biological replicates per condition (not possible to have more, unfortunately), could that raise the issue? 

Also, I got an error:
AttributeError in line 6 of /tools/pipeline-transcriptome-de/Snakefile:
'Workflow' object has no attribute 'overwrite_configfile'
but this was solved by replacing "overwrite_configfile" with "overwrite_configfiles" in the snakefile:
if not workflow.overwrite_configfiles:
    configfile: "config.yml"

Thanks a lot for help!

**Comment by sagrudd** [comment]
Hello @suvimake - I have been able to replicate this error as well and have issued a PR that appears to fix this. Please could you try again and let us know if the updated workflow works?

**Comment by hqs10** [comment]
Dear @sagrudd , Dear @suvimake ,

Please could you share the ideas on how to fix that issue?

Would really appreciate your help.

**Comment by sagrudd** [comment]
This issue appears to be fixed and I cannot replicate the issue with the current version of the pipeline

**Comment by bsipos** [comment]
@suvimake Please make sure that you have the latest version of the pipeline from GitHub and that you use the `--use-conda` flag when you are running `snakemake`.
