### ISSUE TITLE
Error in rule de_analysis: jobid: 9

### ISSUE THREAD

**Issue by MustafaElshani** [nanoporetech/pipeline-transcriptome-de#20]
No matter how hard I try I can't  seem to get over this error

```
Loading counts, conditions and parameters.
Loading annotation database.
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Error in rule de_analysis:
    jobid: 9
    output: de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv
    conda-env: /home/mustafa/pipeline-transcriptome-de/Workspaces/ExperimentPipelines/.snakemake/conda/fe062354
    shell:

    /home/mustafa/pipeline-transcriptome-de/scripts/de_analysis.R

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mustafa/pipeline-transcriptome-de/.snakemake/log/2020-08-26T192935.491547.snakemake.log
```

**Comment by MustafaElshani** [comment]
This issue seems to arise from using Gencode Reference files after switching to ENSMBL it worked

**Comment by MustafaElshani** [comment]
> This issue seems to arise from using Gencode Reference files after switching to ENSMBL it worked

If using GENCODE reference add `--gencode` at the `salmon quant` line on Snakefile, It seperates the | into columns

**Comment by hqs10** [comment]
Hey Mustafa, I am facing a quite similar error. Have you been successful in solving that so far? 
I am suspecting the problem in R - R packages conflict. See below the warning messages:

Warning messages:
1: package ‘GenomicFeatures’ was built under R version 4.0.3
2: package ‘S4Vectors’ was built under R version 4.0.3
3: package ‘IRanges’ was built under R version 4.0.3
4: package ‘GenomeInfoDb’ was built under R version 4.0.3
5: package ‘GenomicRanges’ was built under R version 4.0.3
6: package ‘AnnotationDbi’ was built under R version 4.0.3
7: package ‘Biobase’ was built under R version 4.0.3

**Comment by callumparr** [comment]
What version of salmon are you using? Did you update or downgrade from the one installed in the conda environment? I tried adding --gencode flag to the Snakefile and can it is output to the log when it runs but I still get this error when running the pipeline with gencode transcriptome file.

**Comment by callumparr** [comment]
Update: This does not work. And there are clear reasons why it should not work. --gencode flag only works when using the other mode of salmon, that is first making an index and doing the quasi-mapping. For quant mode --gencode does not work. you will need to manually run salmon on your samples mapped to gencode annotations or you can follow this issue perhaps where they use no standard annotation files and alter the snakefile to handed the different format of gtf. 

https://github.com/nanoporetech/pipeline-transcriptome-de/issues/18#issuecomment-674001168
