### ISSUE TITLE
plot_dtu_res error

### ISSUE THREAD

**Issue by rebeelouise** [nanoporetech/pipeline-transcriptome-de#22]
All good til the last moment...

Does anyone have any experience as to what is throwing this error? 

Config file looks fine... 

`Error in rule plot_dtu_res:
    jobid: 26
    output: de_analysis/dtu_plots.pdf
    shell:
        
    home/pipeline-transcriptome-de/scripts/plot_dtu_results.R
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message`

**Comment by bsipos** [comment]
Hello! Could you please include the command line you have run and more details from the error message?

**Comment by sagrudd** [comment]
@bsipos - I have been able to replicate this issue and have a fix; I'll create a PR later today for this - final testing now
