### ISSUE TITLE
What is different?

### ISSUE THREAD

**Issue by peterkilfeather** [nanoporetech/pipeline-transcriptome-de#23]
What is different between this version and the default pipeline for non-paired samples?

I am comparing littermates of an inbred mouse strain and need to decide on the most appropriate method. 

Thank you,
Peter

**Comment by bsipos** [comment]
Hello,

Please refer to [this document ](https://www.sjsu.edu/faculty/gerstman/StatPrimer/paired.pdf)for a description of paired vs. independent samples.
