### ISSUE TITLE
Fail at write.xlsx for raw salmon counts 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pipeline-transcriptome-de#4]
Hi there, after running the Rmarkdown slave, the execution was halted when running this chunk:

`label: geneCounts (with options)
List of 1
 $ echo: logi FALSE`

`Quitting from lines 246-257 (Nanopore_Transcriptome_Tutorial.Rmd)
Error in .jcheck() :
  Java Exception <no description because toString() failed>.jcall(cell, "V", "setCellValue", value)new("jobjRef", jobj = <pointer: 0x5571a47861f8>, jclass = "java/lang/Throwable")
Calls: <Anonymous> ... .write_block -> mapply -> <Anonymous> -> .jcall -> .jcheck`

I opened the Rmarkdown in Rstudio session and ran each chunk, and again it seems to fail exporting the salmon table out to xlsx.

Is this relating to the memory that java uses? Seems file is too large to export from

This is happening on my MacBook Pro 16GB and on server. 

Is there some upper limit using write.xlsx, the salmon counts is quite large

**Comment by bsipos** [comment]
I think you opened the issue at the wrong repository :)

**Comment by callumparr** [comment]
Oh Indeed, I will copy over to the tutorial one.
