### ISSUE TITLE
Question about input files

### ISSUE THREAD

**Issue by weir12** [nanoporetech/pipeline-transcriptome-de#8]
Hi ：
I have two questions about differential expression：
1.Do I need to filter out low base quality reads（some extremely long ONT reads with low base quality）?
2.Does the sequencing depth of biological replicates require close proximity?
 In other words,I have a biologically repeating sample with a higher depth of sequencing than the other two.Do I need to merge low-depth samples into one?
thanks!

**Comment by bsipos** [comment]
Hi,
1. It is a good idea to use only read with mean base quality > 7. The rest is likely not to map anyway.
2. Please only pool together technical replicates! The depth does not have to be the same, however you will not achieve the same power as when you have high coverage for all biological replicates.
